---
- name: Création du compte bob sur les machines cibles
  hosts: all

  tasks:
    - name: Création du groupe admin
      group:
        name: admin
        state: present

    - name: Création du compte bob
      user:
        name: bob
        groups: ["admin"]
        state: present
