---
- name: Chiffrement d'un mot de passe
  hosts: localhost
  become: no

  vars:
    password: azerty

  tasks:
  - name: Affichage du mot de passe en clair
    debug:
      msg: "Password: {{ password }}"

  - name: Chiffrement et affichage du mot de passe
    debug:
      msg: "Password: {{ password | password_hash('sha512') }}"
