---
- name: Installation/configuration du serveur Apache
  hosts: all

  tasks:
  - name: Installation du package apache2
    package:
      name: "{{ apache_package_name }}"
      state: present

  - name: Activation et démarrage du service apache
    systemd:
      name: "{{ apache_service_name }}"
      state: started
      enabled: yes

  - name: Modification du port d'écoute
    lineinfile:
      dest: "{{ apache_port_file }}"
      regex: ^Listen
      line: "Listen {{ apache_listen_port }}"
    notify: restart_apache

  - name: Recopie du fichier index.html
    copy:
      src: index.html
      dest: "{{ apache_html_files }}"

  handlers:
  - name: Redémarrage du service Apache pour prise en compte des modifs de config.
    systemd:
      name: "{{ apache_service_name }}"
      state: restarted
    listen: restart_apache
