---
- name: Création du compte bob sur les machines cibles
  hosts: all

  tasks:
    - name: Création du groupe admin
      group:
        name: admin
        state: present

    - name: Création du compte bob
      user:
        name: bob
        groups: ["admin"]
        state: present
        password: "{{ bob_password | string | password_hash('sha512') }}"

    - name: Forcer la saisie d'un mot de passe à la première connexion
      shell:
        cmd: chage -d 0 bob
