---
- name: Installation de MariaDB à partir du rôle geerlingguy
  hosts: all

  roles:
    - name: Rôle de Geerlingguy
      role: geerlingguy.mysql
      vars:
        mysql_python_package_debian: python-mysqldb
